# Generated by Django 5.1.5 on 2025-01-27 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('user_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
                ('therapy_issues', models.TextField()),
                ('therapy_approaches', models.TextField()),
                ('budget', models.IntegerField()),
                ('availability', models.CharField(choices=[('Morning', 'Morning'), ('Afternoon', 'Afternoon'), ('Evening', 'Evening'), ('Flexible', 'Flexible')], max_length=10)),
                ('therapist_gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6)),
            ],
            options={
                'verbose_name': 'Therapist Recommendation',
                'verbose_name_plural': 'Therapist Recommendations',
            },
        ),
    ]
